export const BRAND_LIST_REQUEST = 'BRAND_LIST_REQUEST';
export const BRAND_LIST_SUCCESS = 'BRAND_LIST_SUCCESS';
export const BRAND_LIST_FAIL = 'BRAND_LIST_FAIL';
export const BRAND_CREATE_REQUEST = 'BRAND_CREATE_REQUEST';
export const BRAND_CREATE_SUCCESS = 'BRAND_CREATE_SUCCESS';
export const BRAND_CREATE_FAIL = 'BRAND_CREATE_FAIL';

