export const PRODCUTS_BY_CATEGORY_ID_LIST_REQUEST =
  'CATEGORY_LIST_REQUEST';
export const PRODCUTS_BY_CATEGORY_ID_LIST_SUCCESS =
  'CATEGORY_LIST_SUCCESS';
export const PRODCUTS_BY_CATEGORY_ID_LIST_FAIL = 'CATEGORY_LIST_FAIL';
export const PRODCUTS_BY_CATEGORY_ID_LIST_RESET =
  'CATEGORY_LIST_RESET';

export const CATEGORY_LIST_REQUEST = 'CATEGORY_LIST_REQUEST';
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS';
export const CATEGORY_LIST_FAIL = 'CATEGORY_LIST_FAIL';
export const CATEGORY_LIST_RESET = 'CATEGORY_LIST_RESET';

export const SUBCATEGORY_LIST_REQUEST = 'SUBCATEGORY_LIST_REQUEST';
export const SUBCATEGORY_LIST_SUCCESS = 'SUBCATEGORY_LIST_SUCCESS';
export const SUBCATEGORY_LIST_FAIL = 'SUBCATEGORY_LIST_FAIL';
