export const ADDRESS_GET_REQUEST = 'ADDRESS_GET_REQUEST';
export const ADDRESS_GET_SUCCESS = 'ADDRESS_GET_SUCCESS';
export const ADDRESS_GET_FAIL = 'ADDRESS_GET_FAIL';

export const ADDRESS_POST_REQUEST = 'ADDRESS_POST_REQUEST';
export const ADDRESS_POST_SUCCESS = 'ADDRESS_POST_SUCCESS';
export const ADDRESS_POST_FAIL = 'ADDRESS_POST_FAIL';
