export const PRODUCTID_CREATE_REQUEST = 'PRODUCTID_CREATE_REQUEST';
export const PRODUCTID_CREATE_SUCCESS = 'PRODUCTID_CREATE_SUCCESS';
export const PRODUCTID_CREATE_FAIL = 'PRODUCTID_CREATE_FAIL';
export const PRODUCTID_CREATED = 'PRODUCTID_CREATED';

export const PINCODE_CHECK_REQUEST = 'PINCODE_CHECK_REQUEST';
export const PINCODE_CHECK_SUCCESS = 'PINCODE_CHECK_SUCCESS';
export const PINCODE_CHECK_FAIL = 'PINCODE_CHECK_FAIL';
export const PINCODE_CHECKED = 'PINCODE_CHECKED';
