export const REVIEW_GET_REQUEST = 'REVIEW_GET_REQUEST';
export const REVIEW_GET_SUCCESS = 'REVIEW_GET_SUCCESS';
export const REVIEW_GET_FAIL = 'REVIEW_GET_FAIL';

export const REVIEW_POST_REQUEST = 'REVIEW_POST_REQUEST';
export const REVIEW_POST_SUCCESS = 'REVIEW_POST_SUCCESS';
export const REVIEW_POST_FAIL = 'REVIEW_POST_FAIL';
